SonBoutique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('others/', include('others.urls', namespace='others')),
    path('', include('shop.urls', namespace='shop')),
    path('statisticadmin/', include('statisticadmin.urls', namespace='statisticadmin')),
    path('account/', include('account.urls', namespace='account')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse')),
    path('finance/', include('finance.urls', namespace='finance')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'others.views.error_404_view'
handler500 = 'others.views.error_404_view'

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

statisticadmin/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'statisticadmin'

urlpatterns = [
    path('dashboard/', views.home, name='home'),
    path('order/', views.order, name='order'),
    path('order/day/<str:day>/', views.order, name='order_on_day'),
    path('order/month/<str:month>/', views.order, name='order_in_month'),
    path('order/paid/<int:paid>/', views.order, name='paid'),
    path('order-paid/', views.order_paid, name='order_paid'),
    path('stock/', views.stock_list, name='stock_list'),
    path('revenue/', views.revenue, name='revenue'),
    path('expenses/', views.expenses, name='expenses'),
    path('expense-list/', views.expense_list, name='expense-list'),
    path('expense-list/m=<str:month>/', views.expense_list, name='expenses_in_month'),
    path('profit/', views.profit, name='profit'),
]

warehouse/urls.py
from django.urls import path
from . import views

app_name='warehouse'

urlpatterns = [
    path('import/', views.Import, name='import'),
    path('multi-import/', views.load_excel, name='load_excel'),
    path('importing-history/', views.import_list, name='importing-history'),
    path('import-excel/', views.import_by_excel, name='import_by_excel'),

]

statisticadmin/forms.py
from django import forms
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class DateRangeForm(forms.Form):
    start_date = forms.DateField(widget=DateInput())
    end_date = forms.DateField(widget=DateInput())

warehouse/forms.py
from .models import StockIn
from django import forms

class StockInForm(forms.ModelForm):
    class Meta:
        model = StockIn
        fields = ['product', 'origin_price', 'sale_price', 'quantity']

statisticadmin/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from account.check_user import is_admin, is_customer, is_staff, is_staff_view
from orders.models import OrderItem, Order
from finance.models import Expenses
from shop.models import Product
from django.db.models import Sum, Q
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.utils.timezone import datetime
from django.contrib.auth.decorators import permission_required

@user_passes_test(is_staff)
@login_required
def home(request):
    order_items = OrderItem.objects.all()
    products = Product.objects.all()
    orders = Order.objects.all()
    # total orderd items
    total_order_items = order_items.aggregate(total_order=Sum('quantity'))['total_order']
    # total saled items
    total_saled_items = order_items.filter(order__paid=True).aggregate(total_saled=Sum('quantity'))['total_saled']
    # total income of saled items
    income_amounts = "{:,}".format(orders.filter(paid=True).aggregate(income_amounts=Sum('total_price'))['income_amounts'])
    # total stock
    total_stock = products.aggregate(total_stock=Sum('stock'))['total_stock']

    # data for highchart
    select_data = {"create": """strftime('%%d-%%m-%%Y', created)"""}
    # income
    dataset = Order.objects.filter(paid=True).extra(select=select_data).values('create').annotate(
        income=Sum('total_price')).order_by('-create')[:10]
    # total orders by day
    total_order_by_day = Order.objects.filter(paid=True).extra(select=select_data).values('create').annotate(
        total_order=Count('id')).order_by('-create')[:10]
    # total items by day
    total_items_by_day = OrderItem.objects.filter(order__paid=True).extra(select=select_data).values('create').annotate(
        total_items=Sum('quantity')).order_by('-create')[:10]
    # top 5 of the saled items
    total_saled_items_by_type = products.extra(select={"names":"names"}).values('name').annotate(quantity=Sum('saled')).order_by('-quantity')[:5]
    # top 5 of the items in stock
    items_in_stock_by_type = products.extra(select={"names":"names"}).values('name').annotate(quantity=Sum('stock')).order_by('-quantity')[:5]
    context = {
        'total_order_items': total_order_items,
        'total_saled_items': total_saled_items,
        'income_amounts': income_amounts,
        'total_stock': total_stock,
        'orders': orders[:10],
        'dataset': dataset,
        'total_order_by_day': total_order_by_day,
        'total_items_by_day': total_items_by_day,
        'total_saled_items_by_type': total_saled_items_by_type,
        'items_in_stock_by_type': items_in_stock_by_type,

    }
    return render(request,
                  'statisticadmin/dashboard/dashboard.html',
                  context)

# Order List
@user_passes_test(is_staff_view)
@login_required
def order(request, day=None, month=None, paid=None):
    today = datetime.now()
    order_list = Order.objects.all().order_by('paid', '-created')
    title = ''
    amount= ''
    search = request.GET.get('q')
    filter = request.POST.get('pay')
    if filter:
        order_list = order_list.filter(paid=0)
    if search:
        order_list=order_list.filter(phone_number=search)
        amount = 'TỔNG TIỀN ĐÃ MUA {} VND'.format(order_list.aggregate(amount=Sum('total_price'))['amount'])
        title = 'THEO SĐT {}'.format(search)
    else:
        if day:
            order_list = order_list.filter(created__day=day.split('-')[0], created__month=day.split('-')[1], created__year=day.split('-')[2])
            title = 'NGÀY {}'.format(day)
        if month:
            order_list = order_list.filter(created__month=month.split("-")[0], created__year=month.split('-')[1])
            title = 'THÁNG ' + str(month)
        if paid == 1:
            order_list = order_list.filter(paid=True)
        elif paid == 0:
            order_list = order_list.filter(paid=False)
    paginator = Paginator(order_list, 10)  # 10 orders in each page
    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        orders = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        orders = paginator.page(paginator.num_pages)
    context = {
        'page': page,
        'orders': orders,
        'title': title,
        'amount': amount
    }
    return render(request, 'statisticadmin/order/order.html', context)

# Change order paid is True
@user_passes_test(is_staff_view)
@login_required
@require_POST
def order_paid(request):
    order_id = request.POST.get('id')
    if order_id:
        try:
            order = Order.objects.get(id=order_id)
            order.paid = True
            order.save()
            order_items = OrderItem.objects.filter(order=order)
            for order_item in order_items:
                product = Product.objects.get(id=order_item.product.id)
                product.stock -= order_item.quantity
                product.saled += order_item.quantity
                product.save()
            return JsonResponse({'status': 'ok', 'order_id': order_id})
        except:
            pass
    return JsonResponse({'status': 'ko', 'order_id': order_id})

# Stock List
@user_passes_test(is_staff_view)
@login_required
def stock_list(request):
    product_list = Product.objects.filter(available=True, stock__gt=0)
    search = request.GET.get('q')
    if search:
        product_list = product_list.filter(Q(product_code__contains=search) | Q(name__contains=search.upper()) | Q(name__contains=search.lower()))
    paginator = Paginator(product_list, 10)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    context = {
        'products': products,
    }
    return render(request, 'statisticadmin/dashboard/warehouse.html', context)

# Revenue List
@user_passes_test(is_staff_view)
@login_required
def revenue(request):
    search = request.GET.get('d')
    today = datetime.now().strftime('%d-%m-%Y')
    orders = Order.objects.filter(paid=True)
    try:
        # income
        income_total = "{:,}".format(orders.aggregate(income_amounts=Sum('total_price'))['income_amounts'])
        income_today = orders.filter(created__day=today.split('-')[0], created__month=today.split('-')[1], created__year=today.split('-')[2]).aggregate(income_amounts=Sum('total_price'))[
            'income_amounts']
        if income_today is None:
            income_today = 0
        income_month = orders.filter(created__month=today.split('-')[1], created__year=today.split('-')[2]).aggregate(income_amounts=Sum('total_price'))[
            'income_amounts']
        if income_month is None:
            income_today = 0      # order
        order_total = orders.count()
        order_today = orders.filter(created__day=today.split('-')[0], created__month=today.split('-')[1], created__year=today.split('-')[2]).count()
        order_month = orders.filter(created__month=today.split('-')[1], created__year=today.split('-')[2]).count()
        # compare
        income_yesterday = \
        orders.filter(created__day=(int(today.split('-')[0]) - 1), created__month=today.split('-')[1], created__year=today.split('-')[2]).aggregate(income_amounts=Sum('total_price'))[
            'income_amounts']
        income_last_month = \
        orders.filter(created__month=(int(today.split('-')[1]) - 1), created__year=today.split('-')[2]).aggregate(income_amounts=Sum('total_price'))[
            'income_amounts']
        if income_yesterday and income_yesterday != 0:
            income_day_rate = (income_today - income_yesterday) / income_yesterday * 100
        else:
            income_day_rate = 100

        if income_last_month and income_last_month != 0:
            income_month_rate = (income_month - income_last_month) / income_last_month * 100
        else:
            income_month_rate = 100

        income_today = "{:,}".format(income_today)
        income_month = "{:,}".format(income_month)

        # data for highchart
        select_data_by_day = {"create": """strftime('%%d-%%m-%%Y', created)"""}
        select_data_by_month = {"create": """strftime('%%m-%%Y', created)"""}
        # income

        income_month_dataset = orders.extra(select=select_data_by_month).values('create').annotate(income=Sum('total_price')).order_by('-create')[:10]

        income_day_dataset_all = orders.extra(select=select_data_by_day).values('create').annotate(
            income=Sum('total_price')).order_by('-create')
        if search:
            income_day_dataset_all = [income for income in income_day_dataset_all if income['create'] == search]
    except:
        pass


    paginator = Paginator(income_day_dataset_all, 10)  # 10 orders in each page
    page = request.GET.get('page')
    try:
        income_day_dataset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        income_day_dataset = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        income_day_dataset = paginator.page(paginator.num_pages)

    context = {
        'today':today,
        'month': today.split('-')[1] + "-" + today.split('-')[2],
        'income_total': income_total,
        'income_today': income_today,
        'income_month': income_month,
        'order_total': order_total,
        'order_today': order_today,
        'order_month': order_month,
        'income_day_rate': income_day_rate,

warehouse/views.py
from django.shortcuts import render
from .forms import StockInForm
from .models import StockIn
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from openpyxl import load_workbook
from shop.models import Product

# Create your views here.
@login_required
def Import(request):
    if request.method == 'POST':
        form = StockInForm(request.POST)
        if form.is_valid():
            stock_in = form.save(commit=False)
            user = User.objects.get(username=request.user.username)
            stock_in.create_by = user
            stock_in.save()
            messages.success(request, 'Bạn đã nhập {} sản phẩm {} vào kho thành công.'.format(stock_in.quantity, stock_in.product))
        form = StockInForm()
        return render(request, 'warehouse/input.html', {'form': form})
    else:
        form = StockInForm()
    context = {
        'form': form,
    }
    return render(request, 'warehouse/input.html', context)

@login_required
def import_list(request):
    import_list = StockIn.objects.all()
    title = ''
    search = request.GET.get('q')
    if search:
        import_list = import_list.filter(Q(product__name__contains=search.lower()) | Q(product__name__contains=search.upper()) | Q(create_by__username=search))
        title ='TÌM KIẾM THEO {}'.format(search.upper())
    paginator = Paginator(import_list, 15)
    page = request.GET.get('page')
    try:
        imports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        imports = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        imports = paginator.page(paginator.num_pages)
    context = {
        'imports': imports,
        'title': title,
    }
    return render(request, 'warehouse/import_list.html', context)

@login_required
def load_excel(request):
    if request.method == 'GET':
        return render(request, 'warehouse/import_by_excel.html', {'disabled': "disabled=disabled",})
    elif request.method == 'POST':
        excel_file = request.FILES["excel_file"]
        # you may put validations here to check extension or file size

        wb = load_workbook(excel_file)

        # getting a particular sheet by name out of many sheets
        worksheet = wb["Sheet1"]

        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        firstline = True
        for row in worksheet.iter_rows():
            if firstline:  # skip first line
                firstline = False
                continue
            row_data = list()
            for cell in row:
                if cell.value:
                    row_data.append(str(cell.value))
            if row_data != []:
                excel_data.append(row_data)
        context = {
                'excel_data': excel_data,
                'disabled': "disabled=enabled",
            }
        return render(request, 'warehouse/import_by_excel.html', context)

def import_by_excel(request):
    if request.method == 'POST':
        product_code_array = request.POST.getlist('p_code_array[]')
        origin_price_array = request.POST.getlist('o_price_array[]')
        sale_price_array = request.POST.getlist('s_price_array[]')
        quantity_array = request.POST.getlist('quantity_array[]')
        action = request.POST.get('action')
        user = User.objects.get(username=request.user.username)
        if product_code_array and action:
            try:
                if action == "import":
                    for product_code in product_code_array:
                        try:
                            StockIn.objects.create(product=Product.objects.get(product_code=product_code),
                                                   origin_price=origin_price_array[product_code_array.index(product_code)],
                                                   sale_price=sale_price_array[product_code_array.index(product_code)],
                                                   quantity=int(quantity_array[product_code_array.index(product_code)]),
                                                   create_by=user)
                        except Exception as e:
                            print(e)
                            pass
                return JsonResponse({'status': 'ok'})
            except:
                pass
    return JsonResponse({'status': 'ko'})

statisticadmin/templates/statisticadmin/dashboard/dashboard.html
{% extends 'statisticadmin/adminbase.html' %}

{% block title %}
    DASHBOARD
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box widget-inline">
                    <div class="row">
                        <div class="col-lg-3 col-sm-6">
                            <div class="widget-inline-box text-center">
                                <h3 class="m-t-10"><i class="text-primary mdi mdi-access-point-network"></i> <b
                                        data-plugin="counterup"><a
                                        href="{% url "statisticadmin:order" %}">{{ total_order_items }}</a></b></h3>
                                <p class="text-muted">ĐÃ ĐẶT HÀNG</p>
                            </div>
                        </div>

                        <div class="col-lg-3 col-sm-6">
                            <div class="widget-inline-box text-center">
                                <h3 class="m-t-10"><i class="text-custom mdi mdi-airplay"></i> <b
                                        data-plugin="counterup">
                                    <a href="{% url "statisticadmin:paid" 1 %}">{{ total_saled_items }}</a></b></h3>
                                <p class="text-muted">ĐÃ BÁN</p>
                            </div>
                        </div>

                        <div class="col-lg-3 col-sm-6">
                            <div class="widget-inline-box text-center">
                                <h3 class="m-t-10"><i class="text-info mdi mdi-black-mesa"></i> <b
                                        data-plugin="counterup">
                                    <a href="{% url "statisticadmin:revenue" %}">{{ income_amounts }} VND</a></b></h3>
                                <p class="text-muted">DOANH THU</p>
                            </div>
                        </div>

                        <div class="col-lg-3 col-sm-6">
                            <div class="widget-inline-box text-center b-0">
                                <h3 class="m-t-10"><i class="text-danger mdi mdi-cellphone-link"></i> <b
                                        data-plugin="counterup"><a
                                        href="{% url "statisticadmin:stock_list" %}">{{ total_stock }}</a></b></h3>
                                <p class="text-muted">TỒN KHO</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!--end row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="card-box">
                    <h4 class="m-t-0">Doanh thu theo ngày</h4>
                    <div class="text-center">
                        <ul class="list-inline chart-detail-list">
                            <li>
                                <h5 class="font-normal"></h5>
                            </li>
                        </ul>
                    </div>
                    <div id="revenue" style="height: 400px;"></div>
                </div>
            </div> <!-- end col -->

            <div class="col-lg-6">
                <div class="card-box">
                    <h4 class="m-t-0">Số lượng đơn hàng & sản phẩm theo ngày</h4>
                    <div class="text-center">
                        <ul class="list-inline chart-detail-list">
                            <li>
                                <h5 class="font-normal"></h5>
                            </li>
                        </ul>
                    </div>
                    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="card-box">
                    <h4 class="m-t-0">Sản phẩm bán chạy nhất</h4>
                    <div class="text-center">
                        <ul class="list-inline chart-detail-list">
                            <li>
                                <h5 class="font-normal"></h5>
                            </li>
                        </ul>
                    </div>
                    <div id="saled-items-by-type" style="height: 400px;"></div>
                </div>
            </div> <!-- end col -->

            <div class="col-lg-6">
                <div class="card-box">
                    <h4 class="m-t-0">Sản phẩm tồn kho nhiều nhất</h4>
                    <div class="text-center">
                        <ul class="list-inline chart-detail-list">
                            <li>
                                <h5 class="font-normal"></h5>
                            </li>
                        </ul>
                    </div>
                    <div id="items-in-stock-by-type" style="height: 400px;"></div>
                </div>
            </div> <!-- end col -->
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <h4 class="m-t-0">Đơn hàng gần đây</h4>
                    <div class="table-responsive">
                        <table class="table table-hover mails m-0 table table-actions-bar">
                            <thead>
                            <tr>
                                <th width="5%">ID</th>
                                <th width="10%">Tên</th>
                                <th width="20%">Địa chỉ</th>
                                <th>Số điện thoại</th>
                                <th>Tổng tiền</th>
                                <th width="25%">Thời gian đặt hàng</th>
                                <th>Thanh toán</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.first_name }}</td>
                                    <td>{{ order.address }}</td>
                                    <td>{{ order.phone_number }}</td>
                                    <td>{{ order.total_price }} VND</td>
                                    <td>{{ order.created }}</td>
                                    {% if order.paid %}
                                        <td class="paid">
                                            <span class="label label-success">PAID</span>
                                        </td>
                                    {% else %}
                                        <td class="order-id-{{ order.id }}">
                                            <span class="label label-danger">UNPAID</span>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <ul class="pager">
                            <li class="next">
                                <a href="{% url "statisticadmin:order" %}">Xem thêm →</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block domready %}
    <!-- Highchart init -->
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>



    <script>
        Highcharts.chart('revenue', {
            chart: {
                type: 'column'
            },
            title: {
                text: ' '
            },
            xAxis: {
                categories: [
                    {% for entry in dataset %}'{{ entry.create }}'{% if not forloop.last %}, {% endif %}{% endfor %}
                ]
            },
            yAxis: {
                title: {
                    text: 'VND'
                },
            },
            series: [{
                name: 'Doanh thu (VND)',
                data: [
                    {% for entry in dataset %}{{ entry.income }}{% if not forloop.last %}, {% endif %}{% endfor %}
                ],
                color: '#458bc4'
            }]
        });

        Highcharts.chart('container', {
            chart: {
                type: 'spline'
            },
            title: {
                text: ' '
            },
            xAxis: {
                categories: [
                    {% for entry in total_order_by_day %}'{{ entry.create }}'{% if not forloop.last %}, {% endif %}{% endfor %}
                ]
            },
            yAxis: {
                title: {
                    text: 'Số lượng'
                },
            },
            tooltip: {
                crosshairs: true,
                shared: true
            },
            plotOptions: {
                spline: {
                    marker: {
                        radius: 4,
                        lineColor: '#666666',
                        lineWidth: 1
                    }
                }
            },
            series: [{
                name: 'Số đơn hàng',
                marker: {
                    symbol: 'square'
                },
                data: [
                    {% for entry in total_order_by_day %}{{ entry.total_order }}{% if not forloop.last %}, {% endif %}{% endfor %}
                ],

            },
                {
                name: 'Số sản phẩm',
                marker: {
                    symbol: 'square'
                },
                data: [
                    {% for entry in total_items_by_day %}{{ entry.total_items }}{% if not forloop.last %}, {% endif %}{% endfor %}
                ],
                    color: '#4bd396'
            }

            ]
        });

        Highcharts.chart('saled-items-by-type', {
            chart: {
                type: 'column'
            },
            title: {
                text: ' '
            },
            xAxis: {
                categories: [
                    {% for entry in total_saled_items_by_type %}'{{ entry.name }}'{% if not forloop.last %}, {% endif %}{% endfor %}
                ]
            },
            yAxis: {
                title: {
                    text: ''
                },
            },
            series: [{
                name: 'Số lượng (sản phẩm)',
                data: [
                    {% for entry in total_saled_items_by_type %}{{ entry.quantity }}{% if not forloop.last %}, {% endif %}{% endfor %}
                ],
                color: '#31B404'
            }]
        });

        Highcharts.chart('items-in-stock-by-type', {
            chart: {
                type: 'column'
            },
            title: {
                text: ' '
            },
            xAxis: {
                categories: [
                    {% for entry in items_in_stock_by_type %}'{{ entry.name }}'{% if not forloop.last %}, {% endif %}{% endfor %}
                ]
            },
            yAxis: {
                title: {
                    text: ''
                },
            },
            series: [{
                name: 'Số lượng (sản phẩm)',
                data: [
                    {% for entry in items_in_stock_by_type %}{{ entry.quantity }}{% if not forloop.last %}, {% endif %}{% endfor %}
                ],
                color: '#DF7401'
            }]
        });
    </script>
{% endblock %}

statisticadmin/templates/statisticadmin/dashboard/expense-list.html
{% extends "statisticadmin/adminbase.html" %}
{% block title %}DANH SÁCH CHI PHÍ CHI TIẾT{% endblock %}

{% block content %}
    <div class="table-responsive m-b-20">
        <h3 class="m-b-20 header-title">DANH SÁCH CHI PHÍ CHI TIẾT {{ title }}</h3>

        <form action=".">
            <div class="input-group col-md-6">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
            </span>
                <input width="50%" type="text" id="example-input1-group2" name="q" class="form-control"
                       placeholder="Tìm kiếm theo loại chi phí hoặc người nhập">
            </div>
        </form>
        <br>
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="5%">ID</th>
                <th width="30%">Loại chi phí</th>
                <th width="10%">Tháng</th>
                <th width="15%">Tổng tiền (VND)</th>
                <th width="20%">Ghi chú</th>
                <th width="10%">Được tạo bởi</th>
            </tr>
            </thead>


            <tbody>
            <form action="." method="post">
                {% csrf_token %}
                {% for expense in expenses %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ expense.name }}</td>
                        <td>{{ expense.month }}</td>
                        <td>{{ expense.amount }}</td>
                        <td>{{ expense.note }}</td>
                        <td>{{ expense.create_by }}</td>
                    </tr>
                {% endfor %}
            </form>
            </tbody>

        </table>
        {% include "pagination.html" with page=expenses %}

    </div>

{% endblock %}