SonBoutique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('others/', include('others.urls', namespace='others')),
    path('', include('shop.urls', namespace='shop')),
    path('statisticadmin/', include('statisticadmin.urls', namespace='statisticadmin')),
    path('account/', include('account.urls', namespace='account')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse')),
    path('finance/', include('finance.urls', namespace='finance')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'others.views.error_404_view'
handler500 = 'others.views.error_404_view'

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.product_list, name='product_list_all'),
    path('<slug:category_slug>/', views.category, name='product_list_by_category'),
    path('collection/<int:id>/', views.product_list, name='product_list_by_collection'),
    path('collection/list/', views.collection_list, name='collection_list'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('tag/<slug:tag_slug>/', views.product_list, name='post_list_by_tag'),
    path('best-saled/<int:best_saled>/', views.product_list, name='best_saled_product'),

]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 25)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
    <!-- Cart -->
    <section class="section-wrap shopping-cart pt-0">
        <div class="container relative">
            <div class="row">

                <div class="col-md-12">
                    <div class="table-wrap mb-30">
                        <table class="shop_table cart table">
                            <thead>
                            <tr>
                                <th class="product-name" colspan="2">Sản phẩm</th>
                                <th class="product-price">Giá</th>
                                <th class="product-quantity">Số lượng</th>
                                <th class="product-subtotal">Thành tiền</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr class="cart_item">
                                        <td class="product-thumbnail">
                                            <a href="{{ product.get_absolute_url }}">
                                                <img src="
                                                        {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"
                                                     alt="">
                                            </a>
                                        </td>
                                        <td class="product-name">
                                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                        </td>
                                        <td class="product-price">
                                            <span class="amount">{{ item.price }} VND</span>
                                        </td>
                                        <td class="product-quantity">
                                            <div class="quantity buttons_added">
                                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                    <div class="col-sm-8">{{ item.update_quantity_form.quantity }}</div>
                                                    {{ item.update_quantity_form.update }}
                                                    <input type="submit" name="apply_coupon" class="btn btn-md btn-dark" value="Cập nhật">
                                                    {% csrf_token %}
                                                </form>
                                            </div>
                                        </td>
                                        <td class="product-subtotal">
                                            <span class="amount">{{ item.total_price }} VND</span>
                                        </td>
                                        <td class="product-remove">
                                            <a href="{% url "cart:cart_remove" product.id %}" class="remove"
                                               title="Remove this item">
                                                <i class="icon icon_close"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                                <tr>
                                    <td class="cart-subtotal" colspan="2">
                                         <span class="amount">TỔNG TIỀN HÀNG:</span>
                                    </td>
                                    <td colspan="2"></td>
                                    <td class="cart-subtotal">
                                        <span class="amount">{{ cart.get_total_price|floatformat:"0" }} VND</span>
                                    </td>
                                </tr>
                                <tr>
                                     <td class="cart-subtotal" colspan="2">
                                         <span class="amount">GIẢM GIÁ {% if cart.coupon %}[{{ cart.coupon.code }} ({{ cart.coupon.discount }}% off)]{% endif %}:</span>
                                    </td>
                                    <td colspan="2"></td>
                                    <td class="cart-subtotal">
                                        <span class="amount">{{ cart.get_discount|floatformat:"0" }} VND</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="product-subtotal" colspan="2">
                                         <span class="amount">TỔNG THANH TOÁN:</span>
                                    </td>
                                    <td colspan="2"></td>
                                    <td class="product-subtotal">
                                        <span class="amount">{{ cart.get_total_price_after_discount|floatformat:"0" }} VND</span>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>

                    <div class="row mb-50">
                        <div class="col-md-5 col-sm-12">
                            <div class="coupon">
                                <form action="{% url "coupons:apply" %}" method="post">
                                    {{ coupon_apply_form.code }}
                                    <input type="submit" name="apply_coupon" class="btn btn-md btn-dark" value="Áp dụng">
                                    {% csrf_token %}
                                </form>

                            </div>
                        </div>

                        <div class="col-md-7">
                            <div class="actions right">
                                <a href="{% url "shop:product_list_all" %}"><input type="submit" name="update_cart"
                                                                                   value="Tiếp tục mua sắm"
                                                                                   class="btn btn-md btn-dark"></a>
                                <div class="wc-proceed-to-checkout">
                                    <a href="{% url "orders:order_create" %}"
                                       class="btn btn-md btn-color"><span>Thanh toán</span></a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div> <!-- end col -->
            </div> <!-- end row -->


        </div> <!-- end container -->
    </section> <!-- end cart -->

{% endblock %}