SonBoutique/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('others/', include('others.urls', namespace='others')),
    path('', include('shop.urls', namespace='shop')),
    path('statisticadmin/', include('statisticadmin.urls', namespace='statisticadmin')),
    path('account/', include('account.urls', namespace='account')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse')),
    path('finance/', include('finance.urls', namespace='finance')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'others.views.error_404_view'
handler500 = 'others.views.error_404_view'

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.product_list, name='product_list_all'),
    path('<slug:category_slug>/', views.category, name='product_list_by_category'),
    path('collection/<int:id>/', views.product_list, name='product_list_by_collection'),
    path('collection/list/', views.collection_list, name='collection_list'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('tag/<slug:tag_slug>/', views.product_list, name='post_list_by_tag'),
    path('best-saled/<int:best_saled>/', views.product_list, name='best_saled_product'),

]

shop/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class Category(models.Model):
    id = models.AutoField(primary_key=1, auto_created=1)
    parent_id = models.IntegerField()
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True)
    available = models.BooleanField(default=1)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Color(models.Model):
    id = models.AutoField(primary_key=1, auto_created=1, unique=1)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Size(models.Model):
    id = models.AutoField(primary_key=1, auto_created=1, unique=1)
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    product_code = models.CharField(max_length=50, unique=1)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.IntegerField()
    saled = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('-updated',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class ProductImage(models.Model):
    id = models.AutoField(primary_key=1, auto_created=1, unique=1)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

class Comment(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.product)

class Link(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=500)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

class Banner(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField()
    img = models.ImageField(upload_to='banners/%Y/%m/%d', blank=True)
    url = models.CharField(max_length=300, blank=True)
    order = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.name

shop/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Tên*'}
        )
    )

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, ProductImage, Comment, Banner
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count, Q
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Show product list
def  product_list(request, id=None, tag_slug=None, best_saled=None):
    tag = None
    title = 'HÀNG MỚI VỀ'
    product_list = Product.objects.filter(available=True)

    search = request.GET.get('q')
    if search:
        product_list = product_list.filter(Q(name__contains=search.upper()) | Q(name__contains=search.lower()) | Q(product_code__contains=search))
        title = 'SẢN PHẨM TÌM KIẾM THEO "{}"'.format(search)
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        product_list = product_list.filter(tags__in=[tag])
        title = 'Danh sách sản phẩm với ' + tag.name
    if id:
        categories = Category.objects.filter(parent_id=id)
        product_list = product_list.filter(category__in=categories)
        title = '{}'.format(Category.objects.get(id=id).name)

    # get 2 pages of list of best saled products
    if best_saled:
        product_list = product_list.order_by('-saled')[:24]
        title = 'Sản phẩm bán chạy nhất'

    paginator = Paginator(product_list, 12)  # 12 products in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    return render(request,
                  'shop/product/list.html',
                  {'products': products,
                   'tag': tag,
                   'title': title})

def category(request, category_slug=None):
    category = None
    categories = Category.objects.exclude(parent_id=0)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product_list = Product.objects.filter(available=True, category=category)

    paginator = Paginator(product_list, 12)  # 12 products in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    # get tags in category and remove duplicate
    tags = []
    for product in products:
        for tag in product.tags.all():
            if tag not in tags:
                tags.append(tag)

    # best saled
    best_saled_products = product_list.order_by('-saled')[:2]

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'tags': tags,
        'best_saled_products': best_saled_products,
    }


    return render(request, 'shop/product/category.html', context)


def home(request):
    banners = Banner.objects.filter(active=True)
    products = Product.objects.filter(available=True)
    best_saled_products = products.order_by('-saled')[:4]
    products = products[:4]

    context = {
        'products': products,
        'best_saled_products': best_saled_products,
        'banners': banners
    }
    return render(request, 'shop/index.html', context)

# Show product detail
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    #List of active comments for this product
    comments = product.comments.filter(active=True)

    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.product = product
            new_comment.save()
    else:
        comment_form = CommentForm()

    product_images = product.images.all()

    # List of related products
    product_tags_ids = product.tags.values_list('id', flat=True)
    related_products = Product.objects.filter(tags__in=product_tags_ids).exclude(id=product.id)
    related_products = related_products.annotate(same_tags=Count('tags')).order_by('-same_tags')[:8]
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'product_images': product_images,
                   'cart_product_form': cart_product_form,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'related_products': related_products})

def collection_list(request):
    collections = Category.objects.filter(parent_id=0)

    context = {
        'collections': collections
    }
    return render(request, 'shop/collection/collection_list.html', context)

shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}SON BOUTIQUE{% endblock %}

{% block content %}
    <!-- Hero Slider -->
    <section class="section-wrap nopadding">
        <div class="container">
            <div class="entry-slider">
                <div class="flexslider" id="flexslider-hero">
                    <ul class="slides clearfix">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.url }}"><img src="{{ banner.img.url }}" alt=""></a>

                                <div class="hero-holder text-center right-align">
                                    <div class="hero-lines">
                                        <h1 class="hero-heading white">{{ banner.name }}</h1>
                                        <h4 class="hero-subheading white uppercase">{{ banner.content }}</h4>
                                    </div>
                                    <a href="{{ banner.url }}" class="btn btn-lg btn-white"><span>Shop Now</span></a>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div> <!-- end slider -->
        </div>
    </section> <!-- end hero slider -->

    <section class="section-wrap new-arrivals pb-40">
        <div class="container">
            <div class="row heading-row">
                <div class="col-md-12 text-center">
                    <h2 class="heading uppercase">
                        <small>HÀNG MỚI VỀ</small>
                    </h2>
                </div>
            </div>
            <div class="right">
                <a href="{% url "shop:product_list_all" %}"
                   class="btn btn-sm btn-light text-center"><span>Xem thêm >>></span></a>
            </div>
            <br>
            <br>
            <div class="row row-10">
                {% for product in products %}
                    <div class="col-md-3 col-xs-6 animated-from-left">
                        <div class="product-item">
                            <div class="product-img">
                                <a href="{{ product.get_absolute_url }}">
                                    <img width="100%" height="300px" src="{% if product.image %}{{ product.image.url }}
                                    {% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                </a>
                                <div class="product-label">
                                    <span class="sale">sale</span>
                                </div>
                                <div class="product-actions">
                                    <a class="product-add-to-compare" data-toggle="tooltip"
                                       data-placement="bottom" title="Yêu thích">
                                        <i class="fa fa-heart"></i>
                                    </a>
                                </div>
                                <a href="{{ product.get_absolute_url }}" class="product-quickview">Chi tiết</a>
                            </div>
                            <div class="product-details">
                                <h3>
                                    <a class="product-title"
                                       href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <span class="price">
                                  <ins>
                                    <span class="ammount">{{ product.price }} VND</span>
                                  </ins>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div> <!-- end row -->


        </div>
    </section><!-- end new arrivals -->

    <!-- Newsletter -->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="newsletter-box">
                    <h5 class="uppercase">Đăng ký nhận cập nhật thông tin khuyến mãi</h5>
                    <form>
                        <input type="email" class="newsletter-input" placeholder="Email của bạn">
                        <input type="submit" class="newsletter-submit btn btn-md btn-dark" value="Đăng ký">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Best Sellers -->
    <section class="section-wrap pb-0">
        <div class="container">

            <div class="row heading-row">
                <div class="col-md-12 text-center">
                    <h2 class="heading uppercase">
                        <small>BÁN CHẠY NHẤT</small>
                    </h2>
                </div>
            </div>

            <div class="right">
                <a href="{% url "shop:best_saled_product" 1 %}"
                   class="btn btn-sm btn-light text-center"><span>Xem thêm >>></span></a>
            </div>
            <br>
            <br>
            <div class="row row-10">
                {% for product in best_saled_products %}
                    <div class="col-md-3 col-xs-6 animated-from-left">
                        <div class="product-item">
                            <div class="product-img">
                                <a href="{{ product.get_absolute_url }}">
                                    <img width="100%" height="300px" src="{% if product.image %}{{ product.image.url }}
                                    {% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                </a>
                                <div class="product-label">
                                    <span class="sale">sale</span>
                                </div>
                                <div class="product-actions">
                                    <a class="product-add-to-compare" data-toggle="tooltip"
                                       data-placement="bottom" title="Yêu thích">
                                        <i class="fa fa-heart"></i>
                                    </a>
                                </div>
                                <a href="{{ product.get_absolute_url }}" class="product-quickview">Chi tiết</a>
                            </div>
                            <div class="product-details">
                                <h3>
                                    <a class="product-title"
                                       href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <span class="price">
                                  <ins>
                                    <span class="ammount">{{ product.price }} VND</span>
                                  </ins>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div> <!-- end row -->
        </div>
    </section> <!-- end best sellers -->
{% endblock %}